import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LoginNav from "@/app/component/LoginNav";
import NavBar from "../component/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<div className="bg-[#1d1c18]">
<NavBar/>
{children}

</div>
      
  );
}
