import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LoginNav from "@/app/component/LoginNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>
{/* <LoginNav /> */}
{children}

</>
      
  );
}
